server {
    listen 80;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # This line helps React Router work correctly
        try_files $uri $uri/ /index.html;
    }

    # Tells the browser that .js files are actually JavaScript
    include /etc/nginx/mime.types;
}
