name: "Terraform CI/CD Safety Pipeline"

on:
  push:
    branches: [ main, feature/* ]
  pull_request:
    branches: [ main ]

jobs:
  terraform_validation:
    name: "1. Security & Syntax Check"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.8.0"

      - name: Initialize Working Directory
        run: |
          cd retail-devops/Terraform
          terraform init -backend=false

      - name: Verify Formatting Style
        run: |
          cd retail-devops/Terraform
          terraform fmt -check

      - name: Validate Syntax and Arguments
        run: |
          cd retail-devops/Terraform
          terraform validate

  terraform_dry_run:
    name: "2. AWS Simulation Plan"
    runs-on: ubuntu-latest
    needs: terraform_validation
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Full Initialization
        run: |
          cd retail-devops/Terraform
          terraform init

      - name: Run AWS Dry-Run
        run: |
          cd retail-devops/Terraform
          terraform plan -no-color
  terraform_deploy:
    name: "3. Real AWS Deployment"
    runs-on: ubuntu-latest
    needs: terraform_dry_run # Запустится только если Plan прошел без ошибок
    if: github.ref == 'refs/heads/main' && github.event_name == 'push' # Запуск только при пуше в main branch
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Full Initialization
        run: |
          cd retail-devops/Terraform
          terraform init

      - name: Run Real Deployment
        run: |
          cd retail-devops/Terraform
          terraform apply -auto-approve -no-color
