name: "Production: Deploy AWS Infrastructure"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform_deploy:
    name: "Build Infrastructure"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # 1. THIS INSTALLS TERRAFORM (Wrapper disabled to prevent glitches)
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      # 2. AUTOCLEANS FORMATTING
      - name: Force Code Auto-Format
        run: |
          cd retail-devops/Terraform
          terraform fmt

      # 3. INITIALIZES
      - name: Initialize Terraform
        run: |
          cd retail-devops/Terraform
          terraform init

      # 4. DEPLOYS TO AWS
      - name: Apply Infrastructure
        run: |
          cd retail-devops/Terraform
          terraform apply -auto-approve
