name: "Dev Environment: Deploy AWS Infrastructure"

on:
  push:
    branches:
      - dev-branch
  workflow_dispatch:

jobs:
  terraform_deploy:
    name: "Build Infrastructure"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false # Bypasses custom exit-code wrapping glitches

      - name: Initialize Terraform
        run: |
          cd retail-devops/Terraform
          terraform init

      - name: Apply Infrastructure
        run: |
          cd retail-devops/Terraform
          terraform apply -auto-approve -no-color
